config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }

  namespace :admin do
    get '/', to: 'home#index', as: :home
    resources :projects do
      resources :tasks
    end
  end

  namespace :members, as: :member do
    resources :tasks, only: %i[index update]
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#application_error', via: :all
  root 'home#index'
end

app/models/task.rb
class Task < ApplicationRecord
  include StateWorkflow
  FOCUSABLE_TASKS_COUNT = 5

  belongs_to :project
  belongs_to :owner, class_name: 'Member', optional: true

  enum priority: { low: 0, medium: 1, high: 2 }, _suffix: :priority
  auto_increment :scoped_number, scope: :project_id, force: true, lock: false, before: :create

  validates :title, presence: true
  delegate :code, :name, to: :project, prefix: true
  delegate :full_name, to: :owner, prefix: true, allow_nil: true

  scope :priority, -> { order(priority: :desc) }
  scope :focusable, -> { priority.limit(FOCUSABLE_TASKS_COUNT) }

  def identifier
    [project_code, scoped_number].join('-')
  end

  private

  def can_be_started?
    owner.present?
  end
end

app/controllers/admin/tasks_controller.rb
module Admin
  class TasksController < ApplicationController
    include AdminContext
    before_action :set_task, only: %i[show edit update destroy]

    def index
      @pagy, @collection = pagy_countless(tasks_scope)
    end

    def show; end

    def new
      @task = project.tasks.new
    end

    def edit; end

    def create
      @task = project.tasks.new(task_params)

      respond_to do |format|
        if @task.save
          format.html { redirect_to admin_project_task_path(@project, @task), notice: 'Task was successfully created.' }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @task.update(task_params)
          format.html { redirect_to admin_project_tasks_path(@project), notice: 'Task was successfully updated.' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @task.destroy

      respond_to do |format|
        format.html { redirect_to admin_project_tasks_path(@project), notice: 'Task was successfully destroyed.' }
      end
    end

    private

    def tasks_scope
      project.tasks.order(:scoped_number)
    end

    def project
      @project ||= Project.find(params[:project_id])
    end

    def set_task
      @task = project.tasks.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :priority, :owner_id, :description)
    end
  end
end

app/controllers/members/tasks_controller.rb
module Members
  class TasksController < ApplicationController
    include MemberContext
    before_action :set_task, only: %i[update]

    def index
      @pagy, @collection = pagy_countless(tasks_scope)
    end

    def update
      respond_to do |format|
        if @task.update(task_params)
          format.html { redirect_to member_tasks_path(@project), notice: t('pages.member.tasks.success_notice') }
          format.json { render json: { message: t('pages.member.tasks.success_notice') } }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: { message: t('pages.member.tasks.failure_notice') }, status: :unprocessable_entity }
        end
      end
    end

    private

    def tasks_scope
      current_member
        .tasks
        .includes(:project)
        .priority
    end

    def set_task
      @task = current_member.tasks.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:state)
    end
  end
end

app/views/admin/tasks/_form.html.slim
= form_with(model: @task, url: url) do |form|
  - if @task.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.each do |error|
          li = error.full_message

  .form-group.mb-3
    = form.label :title
    = form.text_field :title, class: "form-control"

  .form-group.mb-3
    = form.label :priority, class: "form-label"
    div
      = form.select :priority, enum_options_for_select(Task, :priorities, @task.priority), class: "form-select pt-3"

  .form-group.mb-3
    = form.label :owner, class: "form-label"
    div
      = form.select :owner_id, associated_options_for_select(Member.ordered, :full_name),  include_blank: true, class: "form-select pt-3"

  .form-group.mb-3
    = form.label :description
    = form.text_area :description, class: "form-control"

  .form-group.mb-3
    = form.submit class: 'btn btn-primary'

app/views/admin/tasks/_task.html.slim
div id="#{dom_id task}"
  h2= task.title

  p
    strong Identifier:
    | &nbsp;
    code= task.identifier
  p
    strong Priority:
    | &nbsp;
    code= task.priority
  p
    strong State:
    | &nbsp;
    code= task.state.upcase
  p
    strong Owner:
    | &nbsp;
    code= task.owner_full_name
  p
    strong Description:
    | &nbsp;
    pre
      = truncated_description(task.description)

app/views/admin/tasks/edit.html.slim
.row
  .col-md-6.offset-3
    h1 Edit task

    == render "form", project: @task, url: admin_project_task_path(@project, @task)

    br

  .col-md-6.offset-3
     = link_to "Back to tasks", admin_project_tasks_path(@project)

app/views/admin/tasks/index.html.slim
.row
  .col-md-12
    .row
      .col-md-8
         h1.mb-2 Tasks
      .col-md-4
        = link_to "Back to project", admin_project_path(@project), class: 'btn btn-secondary'
        = link_to "New task", new_admin_project_task_path(@project), class: 'btn btn-primary float-end'

    hr.col-md-12.mb-5
    #tasks
      - if @collection.count.positive?
        - @collection.each do |task|
          == render task
          p
            = link_to "Show this task", admin_project_task_path(@project, task)
          hr.col-md-12.mb-2
        == pagy_bootstrap_nav(@pagy)
      - else
        p.text-center List is empty

app/views/admin/tasks/new.html.slim
.row
  .col-md-6.offset-3
    h1 New task

    == render "form", project: @task, url: admin_project_tasks_path(@project)

    br

  .col-md-6.offset-3
     = link_to "Back to tasks", admin_project_tasks_path(@project)

app/views/admin/tasks/show.html.slim
== render @task
.pb-2
  => link_to "Edit this task", edit_admin_project_task_path(@project, @task)
  ' |
  - unless @task.archived?
    = link_to "Manage tasks", admin_project_tasks_path(@project, @task)
    ' |
  =< link_to "Back to tasks", admin_project_tasks_path(@project)

- unless @task.archived?

  hr.pb-2.col-md-12

  = button_to "Destroy this task",
            admin_project_task_path(@project, @task), method: :delete, class: 'btn btn-danger',
            data: { turbo_confirm: 'Are you sure?' }