config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }

  namespace :admin do
    get '/', to: 'home#index', as: :home
    resources :projects do
      resources :tasks
    end
  end

  namespace :members, as: :member do
    resources :tasks, only: %i[index update]
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#application_error', via: :all
  root 'home#index'
end

app/models/project.rb
class Project < ApplicationRecord
  include StateWorkflow

  has_many :tasks, dependent: :destroy

  enum objective_type: { production: 0, research: 1, education: 2, community: 3 }

  validates :name, presence: true
  validates :code, uniqueness: true, presence: true

  private

  def can_be_started?
    tasks.any?
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < ApplicationController
    include AdminContext
    before_action :set_project, only: %i[show edit update destroy]

    def index
      @pagy, @collection = pagy_countless(projects_scope)
    end

    def show; end

    def new
      @project = Project.new
    end

    def edit; end

    def create
      @project = Project.new(project_params)

      respond_to do |format|
        if @project.save
          format.html { redirect_to admin_project_path(@project), notice: 'Project was successfully created.' }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @project.update(project_params)
          format.html { redirect_to admin_project_path(@project), notice: 'Project was successfully updated.' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @project.destroy

      respond_to do |format|
        format.html { redirect_to admin_projects_path, notice: 'Project was successfully destroyed.' }
      end
    end

    private

    def projects_scope
      Project.order(:code)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :code, :state, :objective_type, :description)
    end
  end
end

app/views/admin/projects/_form.html.slim
= form_with(model: @project, url: url) do |form|
  - if @project.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.each do |error|
          li = error.full_message

  .form-group.mb-3
    = form.label :name
    = form.text_field :name, class: "form-control"

  .form-group.mb-3
    = form.label :code
    = form.text_field :code, class: "form-control"

  .form-group.mb-3
    = form.label :objective_type, class: "form-label"
    div
      = form.select :objective_type, enum_options_for_select(Project, :objective_types, @project.objective_type), class: "form-select pt-3"

  .form-group.mb-3
    = form.label :description
    = form.text_area :description, class: "form-control"

  .form-group.mb-3
    = form.submit class: 'btn btn-primary'

app/views/admin/projects/_project.html.slim
div id="#{dom_id project}"
  h2= project.name
  p
    strong Code:
    | &nbsp;
    code= project.code
  p
    strong State:
    | &nbsp;
    code= project.state.upcase
  p
    strong Objective type:
    | &nbsp;
    code= project.objective_type
  p
    strong Description:
    | &nbsp;
    pre
      = truncated_description(project.description)

app/views/admin/projects/_state_form.html.slim
= form_with(model: @project, url: url) do |form|
  - if @project.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.each do |error|
          li = error.full_message

  .form-group.mb-3
    = form.label :event, value: 'Change state to:',  style: "display: block"
    = form.select :state, possible_state_options_for_select(@project), include_blank: true

  div
    = form.submit value: 'Change state', class: 'btn btn-primary'

app/views/admin/projects/edit.html.slim
h1 Editing project
== render "form", project: @project, url: admin_project_path(@project)

br

div
  => link_to "Show this project", admin_project_path(@project)
  '|
  =< link_to "Back to projects", admin_projects_path

app/views/admin/projects/index.html.slim
.row
  .col-md-12
    .row
      .col-md-9
         h1.mb-2 Projects
      .col-md-3
        = link_to "New project", new_admin_project_path, class: 'btn btn-primary float-end'

    hr.col-md-12.mb-5
    #projects
      - if @collection.count.positive?
        - @collection.each do |project|
          == render project
          p
            = link_to "Show this project", admin_project_path(project)
          hr.col-md-12.mb-2
        == pagy_bootstrap_nav(@pagy)
      - else
        p.text-center List is empty

app/views/admin/projects/new.html.slim
.row
  .col-md-6.offset-3
    h1 New project

    == render "form", project: @project, url: admin_projects_path

    br

  .col-md-6.offset-3
     = link_to "Back to projects", admin_projects_path

app/views/admin/projects/show.html.slim
== render @project
.pb-2
  => link_to "Edit this project", edit_admin_project_path(@project)
  ' |
  - unless @project.archived?
    = link_to "Manage tasks", admin_project_tasks_path(@project)
    ' |
  =< link_to "Back to projects", admin_projects_path

hr.pb-2.col-md-12
- if @project.archived?
  = button_to "Destroy this project",
              admin_project_path(@project), method: :delete, class: 'btn btn-danger',
              data: { turbo_confirm: 'Are you sure?' }
- else
  h2 Manage state
  - if @project.tasks.count.zero?
    b Notice. Add tasks prior to project kick off
  - else
    == render "state_form", project: @project, url: admin_project_path(@project)