config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }

  namespace :admin do
    get '/', to: 'home#index', as: :home
    resources :projects do
      resources :tasks
    end
  end

  namespace :members, as: :member do
    resources :tasks, only: %i[index update]
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#application_error', via: :all
  root 'home#index'
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < ApplicationController
    include AdminContext

    def index
      set_personal_tasks
    end

    private

    def set_personal_tasks
      @personal_tasks = current_member.tasks.focusable
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/views/admin/home/index.html.slim
h1 = t('pages.admin.dashboard.title')
hr.col-md-12.mb-5
.row.g-5
  .col-md-6
    h2= t('pages.admin.dashboard.create')
    p=t('pages.admin.dashboard.create_description')
    ul.icon-list.ps-0
      li.d-flex.align-items-start.mb-1
        = link_to t('shared.links.projects'), admin_projects_path
  .col-md-6
    h2= t('pages.admin.dashboard.latest')
    p= t('pages.admin.dashboard.latest_description')
    - if @personal_tasks.count.positive?
      ul.icon-list.ps-0
        - @personal_tasks.each do |task|
          li.d-flex.align-items-start.mb-1
            = member_task_title(task)
    - else
       p= t('pages.admin.dashboard.latest_tasks_missing')