config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }

  namespace :admin do
    get '/', to: 'home#index', as: :home
    resources :projects do
      resources :tasks
    end
  end

  namespace :members, as: :member do
    resources :tasks, only: %i[index update]
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#application_error', via: :all
  root 'home#index'
end

app/views/layouts/components/_admin_menu.html.slim
li.nav-item
  = link_to t('nav_menu.admin'), admin_home_path, class: 'nav-link px-2 text-white'
li.nav-item
  = link_to t('nav_menu.projects'), member_tasks_path, class: 'nav-link px-2 text-white'

app/views/layouts/components/_navigation.html.slim
header.p-3.text-bg-dark.mb-1
  .col-lg-8.mx-auto
    .container
      .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
        ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
          - if member_signed_in?
            = render "layouts/components/#{current_member.role}_menu"
        .text-end
          - if member_signed_in?
            = link_to t('nav_menu.sign_out'),
                    destroy_member_session_path, data: { "turbo-method": :delete },
                    class: 'btn btn-outline-primary me-2'
          - else
            = link_to t('nav_menu.sign_in'), new_member_session_path, class: 'btn btn-outline-light me-2'
            = link_to t('nav_menu.sign_up'), new_member_registration_path, class: 'btn btn-warning me-2'

app/views/layouts/components/_user_menu.html.slim
li.nav-item
  = link_to t('nav_menu.projects'), member_tasks_path, class: 'nav-link px-2 text-white'